# Generated by Django 3.2.8 on 2021-12-21 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=2)),
                ('phone_no', models.BigIntegerField()),
                ('specialization', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=30)),
                ('mfd_company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=2)),
                ('phone_no', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ser_id', models.AutoField(primary_key=True, serialize=False)),
                ('ser_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_type', models.CharField(max_length=30)),
                ('no_of_beds', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Admitted_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidmgmt.patient')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidmgmt.ward')),
            ],
        ),
    ]
