# Generated by Django 4.0 on 2022-01-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0002_recptionalist_treats_report_prescribed_to_avails'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
