# Generated by Django 4.0 on 2022-01-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0003_patient_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
