# Generated by Django 4.0 on 2022-01-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0004_delete_report_delete_symptom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='admitted_to',
            unique_together={('p', 'ward')},
        ),
        migrations.AlterUniqueTogether(
            name='avails',
            unique_together={('p', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='prescribed_to',
            unique_together={('m', 'p')},
        ),
        migrations.AlterUniqueTogether(
            name='treats',
            unique_together={('d', 'p')},
        ),
    ]
