# Generated by Django 4.0 on 2022-01-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0005_alter_admitted_to_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admitted_to',
        ),
    ]
