# Generated by Django 4.0 on 2022-01-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0007_patient_date_of_admit_patient_date_of_discharge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Date_of_Admit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Date_of_Discharge',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ward',
        ),
    ]
