# Generated by Django 4.0 on 2022-01-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0008_remove_patient_date_of_admit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Date_of_Admit',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='Date_of_Discharge',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covidmgmt.ward'),
        ),
    ]
