# Generated by Django 4.0 on 2022-01-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0010_alter_patient_date_of_admit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
