# Generated by Django 3.2.8 on 2022-01-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0011_alter_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recptionalist',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
