# Generated by Django 4.1.3 on 2022-12-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0012_auto_20220116_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avails',
            name='p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='avails',
            name='service',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ward',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prescribed_to',
            name='m',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prescribed_to',
            name='p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='treats',
            name='d',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='treats',
            name='p',
            field=models.IntegerField(),
        ),
    ]
