# Generated by Django 4.1.3 on 2022-12-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0012_auto_20220116_0527'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avails',
            unique_together=set(),
        ),
    ]
