# Generated by Django 4.1.3 on 2022-12-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0013_alter_avails_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avails',
            unique_together={('p', 'service')},
        ),
    ]
