# Generated by Django 4.1.3 on 2022-12-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0014_alter_avails_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avails',
            name='p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='avails',
            name='service',
            field=models.IntegerField(),
        ),
    ]
