# Generated by Django 4.1.3 on 2022-12-05 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0015_alter_avails_p_alter_avails_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avails',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidmgmt.patient'),
        ),
        migrations.AlterField(
            model_name='avails',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidmgmt.service'),
        ),
    ]
