# Generated by Django 4.1.3 on 2022-12-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0016_alter_avails_p_alter_avails_service'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avails',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='avails',
            name='p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='avails',
            name='service',
            field=models.IntegerField(),
        ),
    ]
