# Generated by Django 4.1.3 on 2022-12-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0017_alter_avails_unique_together_alter_avails_p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avails',
            name='id',
        ),
        migrations.AlterField(
            model_name='avails',
            name='p',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
