# Generated by Django 4.1.3 on 2022-12-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidmgmt', '0018_remove_avails_id_alter_avails_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='avails',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avails',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidmgmt.patient'),
        ),
        migrations.AlterField(
            model_name='avails',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidmgmt.service'),
        ),
        migrations.AlterUniqueTogether(
            name='avails',
            unique_together={('p', 'service')},
        ),
    ]
